apiVersion: v1
kind: LimitRange
metadata:
  name: tcp-lb-container-limits
  namespace: tcp-lb-mini
  labels:
    lab: "3.4"
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 25m
        memory: 32Mi
      default:
        cpu: 100m
        memory: 128Mi
      min:
        cpu: 5m
        memory: 8Mi
      max:
        cpu: "10"
        memory: 1Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: tcp-lb-namespace-quota
  namespace: tcp-lb-mini
  labels:
    lab: "3.4"
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    pods: "100"
